default_install_hook_types:
  - pre-commit
  - pre-push
repos:
- repo: https://github.com/PyCQA/isort
  rev: 5.11.5
  hooks:
  - id: isort
    args: ["--line-width", "119", "--profile", "black"]
    additional_dependencies:
      - "toml>=0.10"
    stages: [commit]
- repo: https://github.com/python/black
  rev: 22.3.0
  hooks:
  - id: black
    args: ["--line-length", "119"]
    stages: [commit]
- repo: https://github.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    args: ["--ignore", "E203,E266,E501,W503", "--max-line-length", "119", "--max-complexity", "18", "--select", "B,C,E,F,W,T4,B9"]
    stages: [commit]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-ast
    stages: [ commit ]
  - id: check-merge-conflict
    stages: [ commit ]
